# Generated by Django 5.0.1 on 2024-02-26 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_organization', '0004_remove_note_star_note_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='starred_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
