# Generated by Django 4.2.7 on 2024-02-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_organization', '0005_alter_note_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
