# Generated by Django 5.0.1 on 2024-02-27 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_organization', '0006_card_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
