# Generated by Django 5.0.1 on 2024-02-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_organization', '0008_card_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to_do', max_length=20),
        ),
    ]
