# Generated by Django 4.2.7 on 2024-03-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_organization', '0009_alter_card_content_alter_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
