# Generated by Django 5.0.3 on 2024-03-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal_organization", "0012_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
