# Generated by Django 4.2.7 on 2024-03-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_organization', '0015_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
